language: python
python:
    - 2.7
    - 3.5

env:
    - NUMPY_VERSION=1.11

cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.conda

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    
    # base python setup
    - conda install --yes numpy=$NUMPY_VERSION nose cython mpi4py
    - conda install --yes h5py pandas scipy pytables pyyaml astropy numba dask sympy
    #
    # test optional HOD data sources
    # - pip install halotools 
    - pip install pfft-python kdcount mpsort pmesh sharedmem bigfile cachey --no-deps
    - pip install https://github.com/bccp/abopt/archive/master.zip
    - pip install .

script:
    - python runtests.py --mpirun='mpirun -np 4' -v

#after_success:
#    - coveralls
    
#notifications:
#  email: false
