language: python
python:
    - 2.7
    - 3.4

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gfortran-4.8
      - swig

env:
    - NUMPY_VERSION=1.11

cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.conda

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda

    # set the c++ and fortran compilers
    - export CXX=g++-4.8
    - export F90=gfortran-4.8

install:
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test

    # base python setup
    - conda install --yes numpy=$NUMPY_VERSION nose cython mpi4py h5py pandas scipy pytables pyyaml astropy numba dask
    - pip install pytest pytest-cov pytest-pipeline coveralls

    # test optional HOD data sources
    - pip install halotools==0.4 # pin on 0.1.x branch

    # test optional Zeldovich data source
    - conda install --yes "swig>=3.0"
    - pip install --no-cache-dir classylss # ignore cache due to binaries

    # nbodykit and requirements
    - pip install --pre pfft-python kdcount mpsort sharedmem bigfile --no-deps
    - pip install pmesh==0.1.23 # pin on 0.1.x branch
    - pip install --pre -r requirements.txt -e . # develop mode to track coverage of subproccess

script:
    - py.test nbodykit --cov=nbodykit --cov-report term-missing
    - bash check_tag.sh nbodykit/version.py

after_success:
    - coveralls

deploy:
    - provider: pypi
      distributions: sdist
      server: https://pypi.python.org/pypi
      user: "nickhand"
      password:
          secure: "HgbpYapyGiOpi51rRGx6H5u1PbkaUp9QgLemg5XjfuKt660QAcDFH3KSDJzl6f2PKvnlkLis8f0fieDYrx8pT3PmuvhwZjQi03ArDpdjVSFn+rQvU1ir3f1Qf1gqdlMWttwfdHjLzHQOF3IMomLGDU6+TXQK+4iRJIprufJFSemNOJ9fTx+Qos6/oWo2q566SLVtdHZZsz1N3tuGzdY9gUGdJLx07g2IsE+WX14v9jwPupgZU+uR1o6twA/I+mvqvbcb9BBKBOQGp7XYtSv61H35SNz+GB6SZeOR3pyG4xKXEB6NsKyIU+7YDPLCwPGAJJZ9rGKviErC8ayTaAhcWDLgLahvWze9IkbGmULoqa4Hs/M5sOkI6ETI7mITl6W9LtFTAwDlUcsZNrtRRYtMM7ygI9xqztU3PuKzzAi50HC7aKRncbj0xhzozCT7ocm1bpICeu+vHh7qsIsVAP4dAC8DqeplN1qSsfkS157/bFYoAWhCJclK1i2KScq7ZQR/Ekc+H0fRBZzVmjbP/2Mv7ukuipn7VBqY5PAoQPWsYLMGutKsRoWcU6TmpL/uxU7iZo2ht8OB7aJ5B+vueqlR7sADw0S37HwtspQGlSQ9OV7KLxLGegGaOu9ajxVo0Bidb+RY+ID4rTSVz4qbbNeJkRD1lhjMG0kCcEyzOwmC+Wc="
      on:
        tags   : true
        condition : $TRAVIS_PYTHON_VERSION = "2.7"

#notifications:
#  email: false
