language: python
python:
    - 2.7
    - 3.4

env:
    - NUMPY_VERSION=1.11

cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.conda

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    - conda install --yes numpy=$NUMPY_VERSION nose cython mpi4py h5py pandas scipy pytables pyyaml astropy numba
    - pip install pytest pytest-cov pytest-pipeline
    - if [ $TRAVIS_PYTHON_VERSION == 2.6 ]; then conda install --yes argparse; fi
    - pip install --pre pfft-python kdcount mpsort pmesh sharedmem bigfile --no-deps
    - pip install --pre -r requirements.txt .
    
script:
    - py.test -s nbodykit/test/test_power.py::TestBianchi1 --cov=nbodykit --cov-report term-missing

#notifications:
#  email: false
