sudo: false
dist: precise

language: python
python:
    - 2.7
    - 3.4

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.9
        - g++-4.9
        - gfortran-4.9
        - swig

env:
    - NUMPY_VERSION=1.11

cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.conda

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda
    - export CXX="g++-5"
    - ldconfig -p | grep fortran

install:
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    - conda install --yes numpy=$NUMPY_VERSION nose cython mpi4py h5py pandas scipy pytables pyyaml astropy numba
    - pip install pytest pytest-cov pytest-pipeline coveralls
    - pip install halotools # test optional halotools packages
    - pip -vvv install --no-binary ':all:' classylss # test optional Zeldovich data source
    - if [ $TRAVIS_PYTHON_VERSION == 2.6 ]; then conda install --yes argparse; fi
    - pip install --pre pfft-python kdcount mpsort pmesh sharedmem bigfile --no-deps
    - pip install --pre -r requirements.txt -e . # develop mode to track coverage of subproccess
    
script:
    - py.test nbodykit --cov=nbodykit --cov-report term-missing

after_success:
    - coveralls
    
#notifications:
#  email: false
